# Generated by Django 4.2.30 on 2026-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoformulario',
            name='texto_pregunta',
            field=models.CharField(default='Texto por defecto', max_length=255, verbose_name='Pregunta para mostrar en la web'),
            preserve_default=False,
        ),
    ]
